#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HellowApp6.Resource", IsApplication=true)]

namespace HellowApp6
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Device = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int edit_field = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int EditMode = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Heart = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Heartbeat = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Identity = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Info = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Location = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int patientdetailsbg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int patientlistbg = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int patientlistitembg = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Phone = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Save = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050009
			public const int btn_addpatient = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int btn_device_okbtn = 2131034113;
			
			// aapt resource value: 0x7f05002a
			public const int btn_inject = 2131034154;
			
			// aapt resource value: 0x7f05002d
			public const int btn_register_patient = 2131034157;
			
			// aapt resource value: 0x7f05001b
			public const int et_age = 2131034139;
			
			// aapt resource value: 0x7f05002c
			public const int et_emergPhone = 2131034156;
			
			// aapt resource value: 0x7f050025
			public const int et_highHr = 2131034149;
			
			// aapt resource value: 0x7f050029
			public const int et_injection = 2131034153;
			
			// aapt resource value: 0x7f050026
			public const int et_lowHr = 2131034150;
			
			// aapt resource value: 0x7f05000e
			public const int et_name = 2131034126;
			
			// aapt resource value: 0x7f05002b
			public const int et_patient_name = 2131034155;
			
			// aapt resource value: 0x7f050019
			public const int ib_age = 2131034137;
			
			// aapt resource value: 0x7f05000d
			public const int ib_device = 2131034125;
			
			// aapt resource value: 0x7f05001d
			public const int ib_edit_age = 2131034141;
			
			// aapt resource value: 0x7f050016
			public const int ib_edit_emerg = 2131034134;
			
			// aapt resource value: 0x7f050028
			public const int ib_edit_hrrange = 2131034152;
			
			// aapt resource value: 0x7f050010
			public const int ib_edit_name = 2131034128;
			
			// aapt resource value: 0x7f050013
			public const int ib_emerg = 2131034131;
			
			// aapt resource value: 0x7f050017
			public const int ib_location = 2131034135;
			
			// aapt resource value: 0x7f05001c
			public const int ib_save_age = 2131034140;
			
			// aapt resource value: 0x7f050015
			public const int ib_save_emerg = 2131034133;
			
			// aapt resource value: 0x7f050027
			public const int ib_save_hrrange = 2131034151;
			
			// aapt resource value: 0x7f05000f
			public const int ib_save_name = 2131034127;
			
			// aapt resource value: 0x7f05000c
			public const int iv_heartrate_monitor_holder = 2131034124;
			
			// aapt resource value: 0x7f050002
			public const int iv_info = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int lv_patient_list = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int scroll = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int sw_monitor = 2131034120;
			
			// aapt resource value: 0x7f050022
			public const int sw_monitor_hr = 2131034146;
			
			// aapt resource value: 0x7f05001a
			public const int tv_age_label = 2131034138;
			
			// aapt resource value: 0x7f050005
			public const int tv_bpm_filler = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int tv_bpm_text = 2131034119;
			
			// aapt resource value: 0x7f05001f
			public const int tv_created = 2131034143;
			
			// aapt resource value: 0x7f05001e
			public const int tv_created_label = 2131034142;
			
			// aapt resource value: 0x7f050012
			public const int tv_current_heartbeat = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int tv_current_heartbeat_label = 2131034129;
			
			// aapt resource value: 0x7f050000
			public const int tv_device_id = 2131034112;
			
			// aapt resource value: 0x7f050014
			public const int tv_emergency_contact_label = 2131034132;
			
			// aapt resource value: 0x7f050023
			public const int tv_highHr_label = 2131034147;
			
			// aapt resource value: 0x7f050021
			public const int tv_hr_label = 2131034145;
			
			// aapt resource value: 0x7f050003
			public const int tv_list_filler = 2131034115;
			
			// aapt resource value: 0x7f050018
			public const int tv_location_label = 2131034136;
			
			// aapt resource value: 0x7f050024
			public const int tv_lowHr_label = 2131034148;
			
			// aapt resource value: 0x7f050020
			public const int tv_monitors_label = 2131034144;
			
			// aapt resource value: 0x7f050004
			public const int tv_name = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int tv_quick_bpm = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_device = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int lviPatient = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PatientDetails = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int register_patient_layout = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
