#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HellowApp6.Resource", IsApplication=true)]

namespace HellowApp6
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int edit_field = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Heart = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Heartbeat = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Info = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Info2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int patientdetailsbg = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int patientlistbg = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int patientlistitembg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Phone = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050013
			public const int ib_button = 2131034131;
			
			// aapt resource value: 0x7f050009
			public const int iv_heartrate_monitor_holder = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int iv_info = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int lv_patient_list = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int scroll = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int sw_monitor = 2131034118;
			
			// aapt resource value: 0x7f050018
			public const int sw_monitor_bp = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int sw_monitor_hr = 2131034135;
			
			// aapt resource value: 0x7f05000d
			public const int tv_additional_details_label = 2131034125;
			
			// aapt resource value: 0x7f050011
			public const int tv_age = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int tv_age_label = 2131034128;
			
			// aapt resource value: 0x7f050003
			public const int tv_bpm_filler = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int tv_bpm_text = 2131034117;
			
			// aapt resource value: 0x7f050015
			public const int tv_created = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int tv_created_label = 2131034132;
			
			// aapt resource value: 0x7f05000c
			public const int tv_current_heartbeat = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int tv_current_heartbeat_label = 2131034123;
			
			// aapt resource value: 0x7f050012
			public const int tv_emergency_contact_label = 2131034130;
			
			// aapt resource value: 0x7f05000a
			public const int tv_id = 2131034122;
			
			// aapt resource value: 0x7f050001
			public const int tv_list_filler = 2131034113;
			
			// aapt resource value: 0x7f05000f
			public const int tv_location = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int tv_location_label = 2131034126;
			
			// aapt resource value: 0x7f050016
			public const int tv_monitors_label = 2131034134;
			
			// aapt resource value: 0x7f050002
			public const int tv_name = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int tv_quick_bpm = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int lviPatient = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PatientDetails = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
